---
- hosts: storage
  tasks:
  - name: Create new directory for lvm
    file:
      path: /data/kubernetes
      state: directory
  - name: Creating volume group
    lvg:
      vg: kubernetes
      pvs: /dev/vdb,/dev/vdc
      pesize: 16
  - name: Creating logical volume
    lvol:
      vg: kubernetes
      lv: data
      size: +100%FREE
      force: yes
  - name: Format to xfs
    filesystem:
      fstype: xfs
      dev: /dev/kubernetes/data
  - name: Mounting LV
    mount:
      path: /data/kubernetes
      src: /dev/kubernetes/data
      fstype: xfs
      state: mounted
  - name: Install NFS server
    apt:
      name: nfs-kernel-server
      update_cache: yes
      state: present
  - name: Change directory ownership
    file:
      path: /data/kubernetes
      owner: nobody
      group: nogroup
      mode: '0777'
  - name: Grant NFS share access
    shell: echo "/data/kubernetes  10.10.0.0/24(rw,sync,no_subtree_check)" >> /etc/exports
  - name: Export NFS share directory
    shell: exportfs -a
  - name: Apply NFS share configuration
    systemd:
      name: nfs-kernel-server
      state: restarted
